#!/usr/bin/env bash
# Fail fast if merged config misses NanoPi R2C critical options.
set -euo pipefail

CFG="${1:?path to .config required}"

[ -f "$CFG" ] || {
    echo "Error: config file not found: $CFG" >&2
    exit 1
}

error_count=0

require_value() {
    local expected="$1" sym
    shift
    for sym in "$@"; do
        grep -Eq "^${sym}=(${expected})$" "$CFG" || {
            echo "Error: expected ${sym}=${expected}" >&2
            return 1
        }
    done
}

require_value y \
    CONFIG_STMMAC_ETH \
    CONFIG_STMMAC_PLATFORM \
    CONFIG_DWMAC_ROCKCHIP \
    CONFIG_MOTORCOMM_PHY \
    CONFIG_REALTEK_PHY \
    CONFIG_WIREGUARD \
    CONFIG_NF_TABLES \
    CONFIG_NF_CONNTRACK \
    CONFIG_NF_NAT \
    CONFIG_BRIDGE \
    CONFIG_VLAN_8021Q \
    CONFIG_XFRM_USER \
    CONFIG_DEBUG_INFO_BTF

require_value y \
    CONFIG_ARM64_ERRATUM_826319 \
    CONFIG_ARM64_ERRATUM_827319 \
    CONFIG_ARM64_ERRATUM_824069 \
    CONFIG_ARM64_ERRATUM_819472 \
    CONFIG_ARM64_ERRATUM_845719 \
    CONFIG_ARM64_ERRATUM_843419 \
    CONFIG_COMPAT \
    CONFIG_KALLSYMS \
    CONFIG_IKCONFIG_PROC \
    CONFIG_INOTIFY_USER \
    CONFIG_FANOTIFY

require_value 4 CONFIG_NR_CPUS
require_value 4 CONFIG_SERIAL_8250_NR_UARTS

require_value y \
    CONFIG_USB_DWC2 \
    CONFIG_USB_DWC2_HOST \
    CONFIG_USB_DWC3 \
    CONFIG_USB_DWC3_HOST \
    CONFIG_USB_XHCI_HCD \
    CONFIG_USB_XHCI_PLATFORM \
    CONFIG_USB_EHCI_HCD \
    CONFIG_USB_EHCI_HCD_PLATFORM \
    CONFIG_USB_OHCI_HCD \
    CONFIG_USB_OHCI_HCD_PLATFORM

require_value y \
    CONFIG_I2C_RK3X \
    CONFIG_MMC \
    CONFIG_MMC_BLOCK \
    CONFIG_MMC_DW \
    CONFIG_MMC_DW_PLTFM \
    CONFIG_MMC_DW_ROCKCHIP \
    CONFIG_PHY_ROCKCHIP_INNO_USB2 \
    CONFIG_PHY_ROCKCHIP_EMMC \
    CONFIG_MFD_RK8XX \
    CONFIG_MFD_RK8XX_I2C \
    CONFIG_REGULATOR_RK808 \
    CONFIG_COMMON_CLK_RK808 \
    CONFIG_CPU_IDLE \
    CONFIG_CPU_IDLE_GOV_MENU \
    CONFIG_ARM_PSCI_CPUIDLE \
    CONFIG_ARM_PSCI_FW \
    CONFIG_SYSCON_REBOOT_MODE \
    CONFIG_CPU_FREQ \
    CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL \
    CONFIG_CGROUPS \
    CONFIG_MEMCG \
    CONFIG_CGROUP_SCHED \
    CONFIG_CGROUP_PIDS \
    CONFIG_CPUSETS \
    CONFIG_CGROUP_BPF

require_value y \
    CONFIG_SCSI \
    CONFIG_BLK_DEV_SD \
    CONFIG_BLK_DEV_INITRD \
    CONFIG_RD_ZSTD \
    CONFIG_USB_STORAGE \
    CONFIG_USB_UAS \
    CONFIG_EXT4_FS \
    CONFIG_KEYS \
    CONFIG_FS_ENCRYPTION \
    CONFIG_FS_ENCRYPTION_ALGS \
    CONFIG_IPV6 \
    CONFIG_NLS \
    CONFIG_NLS_UTF8 \
    CONFIG_MSDOS_PARTITION \
    CONFIG_EFI_PARTITION \
    CONFIG_GPIOLIB \
    CONFIG_GPIO_CDEV \
    CONFIG_GPIO_ROCKCHIP \
    CONFIG_LEDS_GPIO \
    CONFIG_LEDS_TRIGGER_DEFAULT_ON \
    CONFIG_LEDS_TRIGGER_NETDEV \
    CONFIG_INPUT \
    CONFIG_INPUT_EVDEV \
    CONFIG_INPUT_KEYBOARD \
    CONFIG_CPU_THERMAL \
    CONFIG_CPU_FREQ_THERMAL \
    CONFIG_SECURITY_LANDLOCK

require_value y \
    CONFIG_TCP_CONG_CUBIC \
    CONFIG_SWAP \
    CONFIG_CRYPTO_AES \
    CONFIG_CRYPTO_XTS \
    CONFIG_CRYPTO_CHACHA20 \
    CONFIG_ZRAM_BACKEND_LZO \
    CONFIG_ZRAM_DEF_COMP_LZORLE

require_value '"lzo-rle"' CONFIG_ZRAM_DEF_COMP

require_value m \
    CONFIG_USB_RTL8152 \
    CONFIG_KEYBOARD_GPIO \
    CONFIG_TCP_CONG_BBR \
    CONFIG_CRYPTO_DEV_ROCKCHIP \
    CONFIG_DW_WATCHDOG \
    CONFIG_XFRM_INTERFACE \
    CONFIG_TUN \
    CONFIG_VETH \
    CONFIG_MACVLAN \
    CONFIG_IPVLAN \
    CONFIG_ZRAM \
    CONFIG_ZSMALLOC \
    CONFIG_LZO_COMPRESS \
    CONFIG_LZO_DECOMPRESS

require_value 'y|m' \
    CONFIG_BLK_DEV_DM \
    CONFIG_DM_CRYPT \
    CONFIG_IFB \
    CONFIG_NET_SCH_CAKE \
    CONFIG_NET_SCH_FQ_CODEL \
    CONFIG_NET_SCH_INGRESS \
    CONFIG_NET_CLS_U32 \
    CONFIG_NET_CLS_BPF \
    CONFIG_NET_CLS_FLOWER \
    CONFIG_NET_CLS_MATCHALL \
    CONFIG_NET_ACT_MIRRED \
    CONFIG_NET_ACT_POLICE

if [ "$error_count" -gt 0 ]; then
    echo "Error: $error_count config check(s) failed" >&2
    exit 1
fi

echo "R2C config checks passed: $CFG"
